version: '3.8'
services:
#  db:
#    image: postgres
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_HOST_AUTH_METHOD=trust
#    ports:
#      - '5432:5432'
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./hades:/app/hades
      - ./manage.py:/app/manage.py
      - ./users:/app/users
      - ./inventory:/app/inventory
      - ./utils.py:/app/utils.py
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
#    depends_on:
#      - db