# Generated by Django 4.1.1 on 2022-12-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_userprojectmodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymodel',
            name='qr_key',
            field=models.CharField(max_length=512, null=True, unique=True),
        ),
    ]
