# Generated by Django 4.1.1 on 2022-12-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventorymodel_qr_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymodel',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
